[package]
name = "untrusted-app-ocalls"
version = "0.1.0"
edition = "2021"

[lib]
name = "untrusted_app_ocalls"
crate-type = ["rlib"]

[dependencies]
reqwest = { version = "0.12.9", features = ["blocking", "json"] }

[features]
default = ["std"]
std = []